spring.application.name=MagicScreenBackend


spring.datasource.url = jdbc:mysql://localhost:3306/magicscreendb
spring.datasource.username = root
spring.datasource.password =root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


#SMTP Configuration

# Spring Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=your_mail_id
# Note: This must be a 16-character Google App Password, NOT your regular account password
spring.mail.password=your_password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#jwt.secret=cPS5kxRpb9vYhtEnESSyBqCh6aQqB8RNVXvJi0V6Cto
telegram.bot.token=your_telegram_bot_token
telegram.owner.chatId=your_bot_chatod

razorpay.key.id=your_razorpay_key
razorpay.key.secret=your_rasozpay_secret
