spring.application.name=MagicScreenBackend


#spring.datasource.url = jdbc:mysql://localhost:3306/magicscreendb
#spring.datasource.username = root
#spring.datasource.password =root
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true

# Corrected URL structure
spring.datasource.url=your_datasource_link
spring.datasource.username=your_username
spring.datasource.password=your_password
spring.datasource.driver-class-name=org.postgresql.Driver

# ── JPA / Hibernate ──────────────────────────────────────────
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true


#SMTP Configuration

# Spring Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=your_mail@gmail.com
# Note: This must be a 16-character Google App Password, NOT your regular account password
spring.mail.password=your_mail_password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#jwt.secret=cPS5kxRpb9vYhtEnESSyBqCh6aQqB8RNVXvJi0V6Cto
telegram.bot.token=your_bot_token
telegram.owner.chatId=your_chat_Id

razorpay.key.id=your_razorpay_key
razorpay.key.secret=your_razorpay_secret
