spring.application.name=MagicScreenBackend


# Corrected URL structure
spring.datasource.url=YOUR_DATASOURCE_URL
spring.datasource.username=neondb_owner
spring.datasource.password=YOUR_DATABASE_PASSWORD

# ── JPA / Hibernate ──────────────────────────────────────────
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true


#SMTP Configuration

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=YOUR_MAIL_ID
spring.mail.password=YOUR_MAIL_PASSWORD
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000

#jwt.secret=cPS5kxRpb9vYhtEnESSyBqCh6aQqB8RNVXvJi0V6Cto
telegram.bot.token=YOUR_BOT_TOKEN
telegram.owner.chatId=YOUR_CHATID

razorpay.key.id=YOUR_KEY_ID
razorpay.key.secret=YOUR_KEY_SECRET

